Reenable all tests, refactor components.c/h
reutiteuti/logic pull request #2
Opened 2020-06-30 19:21 UTC by svajoklis-1

Silly of me, reenabled all tests, simplified the counter test to remove the sleep and refactored all the rest of the components from components.c/h. Should be all done now.

I have read the thread on ycombinator Hacker News and I have also thought about a connectivity list of some sort. It depends on what is being built though. Right now we are combining elements statically, so the end result would be a single CPU component that could be "fed" instructions opaquely and output some result. VHDL and other hardware description languages (and nand2tetris in the first part) go the route of having a HDL to specify what elements are connected how and then it runs a simulation of those components.

Lots of work in this, will keep thinking about things. A Discord would make sense maybe? Would be nice to have a place to work on ideas that's a bit more convenient than pull requests haha.

2020-06-30 22:31 UTC, rzscheck requested changes
The doComponent() functions need to come before the initComponent() functions because the init() functions call the do() functions

2020-06-30 22:37 UTC, reutiteuti commented
I'm still not understanding the appeal of a netlist - mainly because I don't understand it. Everything I read about them is talking about implementing stuff in an HDL for physical PCBs and FPGAs. Maybe you could help me understand this better.
A Discord would be good. Email me at rzach@outlook.com with your username, then I'll set it up.

2020-07-01 06:38 UTC, svajoklis-1 commented
Interesting point. I did move the create* functions above others. It wouldn't make sense to move the "do" above "init" since it's initialization (doesn't matter it runs the do code), it feels like semantically it would make more sense to have inits higher. Not a hugely important detail though :smile:

2020-07-01 21:55 UTC, merged

2020-07-01 21:55 UTC, reutiteuti commented
Silly me. I forgot that the .h files are basically a forward declaration. Thanks!